name: Selenium Automation Tests

on:
  push:
    branches: [feature/test]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
        tag:
            description: "Etiqueta de prueba para ejecutar (ej. @login, @smoke)"
            required: true
            default: "@login"
            type: string

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: markhobson/maven-chrome:jdk-21
      options: -u root

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verificar Java
        run: java -version

      - name: Ejecutar pruebas
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=/var/maven/.m2/repository"
          TAGS: ${{ inputs.tags || '@login' }}
        run: mvn clean verify -Dcucumber.filter.tags="$TAGS" -Dheadless=true

      - name: Archivar reporte HTML de Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/site/cucumber/cucumber-html-reports/
          if-no-files-found: ignore

      - name: Archivar artefactos generales
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/build/
          if-no-files-found: ignore

      - name: Publicar reporte Cucumber en checks
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: target/build/cucumber.json
